databases:
  - name: oneonone
    plan: free
    databaseName: oneonone
    user: my_user

services:
  - type: web
    plan: free
    name: oneonone
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn p2.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: oneonone
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4